const GROQ_MODEL = "llama-3.3-70b-versatile";

function scriptPrompt(job) {
  return `You are writing the storyboard script for a ${job.duration_target}-second cinematic recruitment marketing video in ${job.aspect_ratio} aspect ratio. Each scene's background will be generated by an AI video model from your visual_description, so describe camera-friendly cinematic motion (e.g. "slow drone push over cruise ship deck at sunset"), not text or logos. Every number and name you output in on_screen_text or voiceover_line MUST exactly match the source data below - do not invent, round, or omit any of it.

Source data:
- Category: ${job.category}
- Client / property / cruise line name: ${job.client_name}
- Role: ${job.role}
- Salary: ${job.salary || "not specified"}
- Contract length: ${job.contract_length || "not specified"}
- Location: ${job.location || "not specified"}
- Benefits: ${job.benefits || "not specified"}
- Requirements: ${job.requirements || "not specified"}
- Application deadline: ${job.application_deadline || "not specified"}
- Extra notes: ${job.extra_notes || "none"}

Respond with ONLY valid JSON (no markdown fences, no commentary) matching this shape:
{
  "headline": "short punchy on-screen title",
  "cta": "final call-to-action line",
  "scenes": [
    {
      "scene_number": 1,
      "visual_description": "cinematic camera motion/subject for the AI video model to generate, no text or logos",
      "on_screen_text": "exact text overlay for this scene, or empty string",
      "voiceover_line": "narration line for this scene, or empty string",
      "duration_seconds": 5
    }
  ]
}

The scene duration_seconds values MUST sum to exactly ${job.duration_target}. Use 6-10 scenes. Make sure the role, client name, salary, contract length, and deadline each appear as on_screen_text in at least one scene, worded exactly as given.`;
}

export async function generateScript(job, env) {
  const resp = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      Authorization: `Bearer ${env.GROQ_API_KEY}`,
    },
    body: JSON.stringify({
      model: env.GROQ_MODEL ?? GROQ_MODEL,
      response_format: { type: "json_object" },
      messages: [{ role: "user", content: scriptPrompt(job) }],
    }),
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Groq API error ${resp.status}: ${text}`);
  }

  const data = await resp.json();
  const text = data.choices?.[0]?.message?.content ?? "";
  return JSON.parse(text);
}
